import type { Order as AdminOrder, OrderMethod } from '../../types';
import type { CreateOrderInput, Order as SellerOrder } from '../../portals/seller/types';
import type {
  CreateManualMarketplaceOrderInput,
  CreateManualMarketplaceOrderRpcInput,
  CreateSellerOrderRpcInput,
  SellerSafeOrderRow,
  SupabaseOrderHistoryRow,
  SupabaseOrderRow,
} from '../types/supabase-orders';

const method = (deliveryMethod: string | null): OrderMethod =>
  deliveryMethod === 'Xbox' ? 'Xbox' : deliveryMethod === 'PSN' ? 'PSN' : 'Epic';

export const mapAdminOrderRow = (
  row: SupabaseOrderRow,
  history: SupabaseOrderHistoryRow[] = [],
): AdminOrder => ({
  id: row.id,
  databaseId: row.id,
  orderNumber: row.order_number,
  source: 'supabase',
  sellerId: row.seller_id || '',
  supplierId: row.supplier_id || '',
  platformId: row.platform_id || undefined,
  platformName: row.platform_name || undefined,
  categoryId: row.category_id,
  categoryName: row.category_name || undefined,
  skuId: row.sku_id,
  productName: row.product_name || undefined,
  orderEntryMode: row.order_entry_mode,
  manualProductName: row.manual_product_name || undefined,
  buyerName: row.buyer_name || undefined,
  buyerReference: row.buyer_reference || undefined,
  orderDate: row.order_date || undefined,
  packageName: row.package_label || undefined,
  deliveryMethod: row.delivery_method || undefined,
  customer: row.customer_username || undefined,
  loginEmail: row.login_email || undefined,
  twoFactorNotes: row.two_factor_notes || undefined,
  sellerNotes: row.seller_notes || undefined,
  internalNotes: row.internal_notes || undefined,
  salePrice: Number(row.sale_price),
  supplierCost: Number(row.supplier_cost),
  sellingFeeAmount: Number(row.selling_fee_amount),
  withdrawalFeeAmount: Number(row.withdrawal_fee_amount),
  netRevenue: Number(row.net_revenue),
  profit: Number(row.profit),
  refundDetails: row.refund_type && row.refund_reason && row.refunded_amount !== null && row.refunded_at ? { type: row.refund_type, reason: row.refund_reason, amount: Number(row.refunded_amount), currency: 'USD', refundedAt: row.refunded_at, refundedBy: row.refunded_by } : null,
  status: row.status,
  value: Number(row.sale_price),
  cost: Number(row.supplier_cost),
  method: method(row.delivery_method),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  credentials: {
    username: row.login_email || '',
    password: row.account_password || '',
    twoFactor: row.two_factor_notes || undefined,
    gamertag: row.customer_username || undefined,
  },
  chat: [],
  history: history.filter((item) => item.order_id === row.id).map((item) => ({
    status: item.status,
    timestamp: item.created_at,
    note: item.note || undefined,
    changedBy: item.changed_by,
  })),
});

export const mapSellerSafeOrderRow = (row: SellerSafeOrderRow): SellerOrder => ({
  id: row.id,
  databaseId: row.id,
  orderNumber: row.order_number,
  source: 'supabase',
  sellerId: row.seller_id || '',
  platformId: row.platform_id || undefined,
  platform: row.platform_name || 'Unknown',
  platformName: row.platform_name || undefined,
  categoryId: row.category_id,
  categoryName: row.category_name || undefined,
  skuId: row.sku_id,
  product: row.manual_product_name || [row.product_name, row.package_label].filter(Boolean).join(' - ') || 'Unknown',
  productName: row.product_name || undefined,
  orderEntryMode: row.order_entry_mode,
  manualProductName: row.manual_product_name || undefined,
  buyerName: row.buyer_name || undefined,
  buyerReference: row.buyer_reference || undefined,
  orderDate: row.order_date || undefined,
  packageName: row.package_label || undefined,
  customer: row.buyer_name || row.customer_username || '',
  status: row.status,
  price: Number(row.sale_price),
  salePrice: Number(row.sale_price),
  date: row.created_at,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
  deliveryMethod: row.delivery_method || undefined,
  email: row.login_email || undefined,
  loginEmail: row.login_email || undefined,
  password: row.account_password || undefined,
  twoFactorNotes: row.two_factor_notes || undefined,
  sellerNotes: row.seller_notes || undefined,
  history: [{ status: row.status, timestamp: row.updated_at }],
});

export const mapCreateOrderInputToRpc = (input: CreateOrderInput): CreateSellerOrderRpcInput => ({
  p_platform_id: input.platformId,
  p_category_id: input.categoryId,
  p_sku_id: input.skuId,
  p_login_email: input.loginEmail.trim(),
  p_account_password: input.password,
  p_seller_notes: input.sellerNotes?.trim() || '',
  p_buyer_reference: input.buyerReference?.trim() || '',
  p_sale_price: input.salePrice,
});

export const mapManualMarketplaceOrderInputToRpc = (
  input: CreateManualMarketplaceOrderInput,
): CreateManualMarketplaceOrderRpcInput => ({
  p_platform_id: input.platformId,
  p_order_date: input.orderDate,
  p_product_name: input.productName.trim(),
  p_buyer_name: input.buyerName.trim(),
  p_login_email: input.loginEmail.trim(),
  p_account_password: input.password,
  p_seller_notes: input.sellerNotes?.trim() || '',
  p_buyer_reference: input.buyerReference?.trim() || '',
  p_sale_price: input.salePrice,
});
