import { useEffect, useState, type ChangeEvent } from 'react';
import { Button, Input, Modal } from '../../../../components/ui';
import { knowledgeBaseAttachmentService } from '../../../../shared/services/knowledgeBaseAttachmentService';
import type { KnowledgeBaseAttachment } from '../../../../shared/types/knowledge-base';

const images = new Set(['image/png','image/jpeg','image/webp','image/gif']);
export const InlineImageDialog = ({ isOpen, articleId, onClose, onInsert }: { isOpen: boolean; articleId: string | null; onClose: () => void; onInsert: (attachment: KnowledgeBaseAttachment, alt: string, caption: string) => void }) => {
  const [items,setItems]=useState<KnowledgeBaseAttachment[]>([]); const [selected,setSelected]=useState<string>(''); const [alt,setAlt]=useState(''); const [caption,setCaption]=useState(''); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!isOpen||!articleId)return;setError(null);void knowledgeBaseAttachmentService.getArticleAttachments(articleId).then((next)=>setItems(next.filter((item)=>images.has(item.mimeType)))).catch(()=>setError('Unable to load image attachments.'));},[isOpen,articleId]);
  const upload=async()=>{if(!articleId||!file)return;setBusy(true);setError(null);try{const item=await knowledgeBaseAttachmentService.uploadArticleAttachment(articleId,file);if(!images.has(item.mimeType))throw new Error('Only image attachments can be inserted.');setItems((current)=>[...current,item]);setSelected(item.id);setFile(null);}catch(e){setError(e instanceof Error?e.message:'Unable to upload image.');}finally{setBusy(false);}};
  const insert=()=>{const item=items.find((candidate)=>candidate.id===selected);if(!item||!alt.trim()){setError('Select an image and provide alternative text.');return;}onInsert(item,alt.trim(),caption.trim());setAlt('');setCaption('');setSelected('');onClose();};
  return <Modal isOpen={isOpen} onClose={()=>!busy&&onClose()} title="Insert Image"><div className="mt-4 space-y-4">{!articleId?<p className="text-sm kb-muted">Save the article before uploading or inserting images.</p>:<><div className="max-h-44 space-y-2 overflow-y-auto">{items.length?items.map((item)=><label key={item.id} className="flex cursor-pointer items-center gap-2 rounded border kb-border p-2 text-sm kb-primary"><input type="radio" checked={selected===item.id} onChange={()=>setSelected(item.id)}/><span className="min-w-0 break-words">{item.fileName} Â· {new Date(item.createdAt).toLocaleString()}</span></label>):<p className="text-sm kb-muted">No image attachments are available yet.</p>}</div><div className="flex flex-col gap-2 sm:flex-row"><input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={(e: ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)} className="text-sm"/><Button size="sm" variant="secondary" onClick={()=>void upload()} disabled={!file||busy}>{busy?'Uploading...':'Upload image'}</Button></div><Input label="Alternative Text" value={alt} onChange={(e: ChangeEvent<HTMLInputElement>)=>setAlt(e.target.value)} placeholder="Describe what is shown in the image"/><Input label="Caption (optional)" value={caption} onChange={(e: ChangeEvent<HTMLInputElement>)=>setCaption(e.target.value)} placeholder="Additional explanation shown beneath the image"/>{error&&<p role="alert" className="text-sm kb-error-text">{error}</p>}</>}</div><div className="mt-6 flex justify-end gap-3"><Button variant="secondary" onClick={onClose} disabled={busy}>Cancel</Button><Button onClick={insert} disabled={!articleId||busy}>Insert Image</Button></div></Modal>;
};


