export interface TranslationDictionary {
  common: { save:string; cancel:string; confirm:string; close:string; open:string; edit:string; delete:string; create:string; add:string; remove:string; update:string; copy:string; retry:string; back:string; continue:string; apply:string; clear:string; reset:string; download:string; upload:string; view:string; search:string; filter:string; export:string; loading:string; saving:string; updating:string; deleting:string; uploading:string; noResults:string; noData:string; error:string; required:string; optional:string; };
  navigation: { overview:string; orders:string; myOrders:string; createOrder:string; giftService:string; fnShop:string; refundedOrders:string; transactions:string; analytics:string; knowledgeBase:string; templates:string; pricing:string; platforms:string; users:string; notifications:string; settings:string; auditLog:string; operations:string; system:string; more:string; adminPortal:string; sellerPortal:string; switchPortal:string; };
  profile: { interfaceLanguage:string; languageHelp:string; signOut:string; closeNavigation:string; openNavigation:string; };
  orders: { management:string; searchOrders:string; searchPlaceholder:string; clearFilters:string; allStatuses:string; dateFrom:string; dateTo:string; invalidDateRange:string; showing:string; of:string; loadingOrders:string; noOrdersYet:string; noOrdersMatch:string; viewDetails:string; notAvailable:string; unassigned:string; unknown:string; website:string; product:string; buyer:string; buyerReference:string; seller:string; supplier:string; value:string; created:string; status:string; revenue:string; spentOnSuppliers:string; orderDetails:string; createOrder:string; createNewOrder:string; selectPlatform:string; selectCategory:string; selectProduct:string; selectSeller:string; platform:string; category:string; skuProduct:string; accountLogin:string; password:string; salePrice:string; notes:string; buyerName:string; orderDate:string; submitOrder:string; submitting:string; manualMarketplace:string; catalog:string; exportExcel:string; exporting:string; refresh:string; notificationsDescription:string; markAllRead:string; marking:string; loadMore:string; live:string; connecting:string; reconnecting:string; offline:string; orderUnavailable:string; openOrderFailed:string; };
  refund: { details:string; full:string; partial:string; type:string; amount:string; reason:string; explain:string; fullHelp:string; maxPartial:string; addDetails:string; editDetails:string; confirm:string; processing:string; recordedHelp:string; reverse:string; reverseHelp:string; confirmReversal:string; reversing:string; legacy:string; legacyHelp:string; unknownUser:string; };
  supplierAssignment: { reassign:string; assign:string; select:string; noSupplier:string; saving:string; };
  history: { title:string; orderRefunded:string; refundUpdated:string; refundReversed:string; changedBy:string; timeline:string; };
  chat: { title:string; loading:string; empty:string; refresh:string; input:string; send:string; sending:string; hint:string; tooLong:string; live:string; connecting:string; reconnecting:string; offline:string; edited:string; admin:string; seller:string; };
}

export const en: TranslationDictionary = {
  common: { save:'Save', cancel:'Cancel', confirm:'Confirm', close:'Close', open:'Open', edit:'Edit', delete:'Delete', create:'Create', add:'Add', remove:'Remove', update:'Update', copy:'Copy', retry:'Retry', back:'Back', continue:'Continue', apply:'Apply', clear:'Clear', reset:'Reset', download:'Download', upload:'Upload', view:'View', search:'Search', filter:'Filter', export:'Export', loading:'Loading...', saving:'Saving...', updating:'Updating...', deleting:'Deleting...', uploading:'Uploading...', noResults:'No results', noData:'No data available', error:'Something went wrong', required:'Required', optional:'Optional' },
  navigation: { overview:'Overview', orders:'Orders', myOrders:'My Orders', createOrder:'Create Order', giftService:'Gift Service', fnShop:'FN Shop', refundedOrders:'Refunded Orders', transactions:'Transactions', analytics:'Analytics', knowledgeBase:'Knowledge Base', templates:'Templates', pricing:'Pricing & SKUs', platforms:'Platforms', users:'Users', notifications:'Notifications', settings:'Settings', auditLog:'Audit Log', operations:'Operations', system:'System', more:'More', adminPortal:'Admin Portal', sellerPortal:'Seller Portal', switchPortal:'Switch Portal' },
  profile: { interfaceLanguage:'Interface Language', languageHelp:'Choose the language used by the dashboard interface.', signOut:'Sign Out', closeNavigation:'Close navigation', openNavigation:'Open navigation' },
  orders: { management:'Manage and track all platform orders.', searchOrders:'Search orders', searchPlaceholder:'Search orders...', clearFilters:'Clear filters', allStatuses:'All statuses', dateFrom:'Date from', dateTo:'Date to', invalidDateRange:'Date From must be on or before Date To.', showing:'Showing', of:'of', loadingOrders:'Loading orders...', noOrdersYet:'No orders yet.', noOrdersMatch:'No orders match the selected filters.', viewDetails:'View details', notAvailable:'Not available', unassigned:'Unassigned', unknown:'Unknown', website:'Website', product:'Product', buyer:'Buyer', buyerReference:'Buyer Name / Order ID', seller:'Seller', supplier:'Supplier', value:'Value', created:'Created', status:'Status', revenue:'Revenue', spentOnSuppliers:'Spent on Suppliers', orderDetails:'Order Details', createOrder:'Create Order', createNewOrder:'Create New Order', selectPlatform:'Select Platform', selectCategory:'Select Category', selectProduct:'Select Product', selectSeller:'Select Seller', platform:'Platform', category:'Category', skuProduct:'SKU / Product', accountLogin:'Account Login', password:'Password', salePrice:'Sale Price (USD)', notes:'Notes', buyerName:'Buyer Name', orderDate:'Order Date', submitOrder:'Submit Order', submitting:'Submitting...', manualMarketplace:'Manual Marketplace', catalog:'Catalog', exportExcel:'Export Excel', exporting:'Exporting...', refresh:'Refresh', notificationsDescription:'Order chat updates for your account.', markAllRead:'Mark all as read', marking:'Marking...', loadMore:'Load more', live:'Live', connecting:'Connecting', reconnecting:'Reconnecting', offline:'Offline', orderUnavailable:'This order is no longer available.', openOrderFailed:'Unable to open this order. Please try again.' },
  refund: { details:'Refund Details', full:'Full Refund', partial:'Partial Refund', type:'Refund Type', amount:'Refunded Amount', reason:'Refund Reason', explain:'Explain why this Order was refunded', fullHelp:'The full Order sale amount will be recorded automatically.', maxPartial:'Maximum partial refund', addDetails:'Add Refund Details', editDetails:'Edit Refund Details', confirm:'Confirm Refund', processing:'Processing...', recordedHelp:'This records the Order as refunded. It does not perform the refund on the marketplace.', reverse:'Reverse Refunded Status', reverseHelp:'This corrects the dashboard status and clears active refund metadata. It does not reverse a marketplace payment.', confirmReversal:'Confirm Reversal', reversing:'Reversing...', legacy:'Legacy refund', legacyHelp:'Detailed refund information was not recorded for this Order.', unknownUser:'Unknown user' },
  supplierAssignment: { reassign:'Reassign Supplier', assign:'Assign Supplier', select:'Select supplier', noSupplier:'No active supplier users are available.', saving:'Saving...' },
  history: { title:'Order History', orderRefunded:'Order refunded', refundUpdated:'Refund details updated', refundReversed:'Refunded status reversed', changedBy:'Changed by', timeline:'Timeline' },
  chat: { title:'Order Chat', loading:'Loading messages...', empty:'No messages yet', refresh:'Refresh messages', input:'Type a message...', send:'Send', sending:'Sending...', hint:'Ctrl/Cmd+Enter to send', tooLong:'Message cannot exceed 5000 characters.', live:'Live', connecting:'Connecting', reconnecting:'Reconnecting...', offline:'Offline', edited:'Edited', admin:'Admin', seller:'Seller' },
};
