import type { TranslationDictionary } from './en';

export const sr: TranslationDictionary = {
  common: { save:'Sačuvaj', cancel:'Otkaži', confirm:'Potvrdi', close:'Zatvori', open:'Otvori', edit:'Izmeni', delete:'Obriši', create:'Kreiraj', add:'Dodaj', remove:'Ukloni', update:'Ažuriraj', copy:'Kopiraj', retry:'Pokušaj ponovo', back:'Nazad', continue:'Nastavi', apply:'Primeni', clear:'Očisti', reset:'Poništi', download:'Preuzmi', upload:'Otpremi', view:'Prikaži', search:'Pretraga', filter:'Filter', export:'Izvezi', loading:'Učitavanje...', saving:'Čuvanje...', updating:'Ažuriranje...', deleting:'Brisanje...', uploading:'Otpremanje...', noResults:'Nema rezultata', noData:'Nema dostupnih podataka', error:'Došlo je do greške', required:'Obavezno', optional:'Opciono' },
  navigation: { overview:'Pregled', orders:'Porudžbine', myOrders:'Moje porudžbine', createOrder:'Nova porudžbina', giftService:'Usluga poklona', fnShop:'FN Shop', refundedOrders:'Refundirane porudžbine', transactions:'Transakcije', analytics:'Analitika', knowledgeBase:'Baza znanja', templates:'Šabloni', pricing:'Cene i proizvodi', platforms:'Platforme', users:'Korisnici', notifications:'Obaveštenja', settings:'Podešavanja', auditLog:'Evidencija', operations:'Operacije', system:'Sistem', more:'Još', adminPortal:'Admin portal', sellerPortal:'Portal prodavca', switchPortal:'Promeni portal' },
  profile: { interfaceLanguage:'Jezik interfejsa', languageHelp:'Izaberite jezik interfejsa kontrolne table.', signOut:'Odjavi se', closeNavigation:'Zatvori navigaciju', openNavigation:'Otvori navigaciju' },
  orders: { management:'Upravljajte i pratite sve porudžbine na platformama.', searchOrders:'Pretraga porudžbina', searchPlaceholder:'Pretražite porudžbine...', clearFilters:'Očisti filtere', allStatuses:'Svi statusi', dateFrom:'Datum od', dateTo:'Datum do', invalidDateRange:'Datum od mora biti pre ili na datum do.', showing:'Prikazano', of:'od', loadingOrders:'Učitavanje porudžbina...', noOrdersYet:'Još nema porudžbina.', noOrdersMatch:'Nema porudžbina koje odgovaraju izabranim filterima.', viewDetails:'Prikaži detalje', notAvailable:'Nije dostupno', unassigned:'Nije dodeljeno', unknown:'Nepoznato', website:'Platforma', product:'Proizvod', buyer:'Kupac', buyerReference:'Ime kupca / ID porudžbine', seller:'Prodavac', supplier:'Dobavljač', value:'Vrednost', created:'Kreirano', status:'Status', revenue:'Prihod', spentOnSuppliers:'Troškovi dobavljača', orderDetails:'Detalji porudžbine', createOrder:'Nova porudžbina', createNewOrder:'Kreiraj novu porudžbinu', selectPlatform:'Izaberite platformu', selectCategory:'Izaberite kategoriju', selectProduct:'Izaberite proizvod', selectSeller:'Izaberite prodavca', platform:'Platforma', category:'Kategorija', skuProduct:'SKU / proizvod', accountLogin:'Prijava na nalog', password:'Lozinka', salePrice:'Prodajna cena (USD)', notes:'Napomene', buyerName:'Ime kupca', orderDate:'Datum porudžbine', submitOrder:'Kreiraj porudžbinu', submitting:'Kreiranje...', manualMarketplace:'Ručna marketplace porudžbina', catalog:'Katalog', exportExcel:'Izvezi u Excel', exporting:'Izvoz...', refresh:'Osveži', notificationsDescription:'Ažuriranja četa porudžbina za vaš nalog.', markAllRead:'Označi sve kao pročitano', marking:'Označavanje...', loadMore:'Učitaj još', live:'Uživo', connecting:'Povezivanje', reconnecting:'Ponovno povezivanje', offline:'Van mreže', orderUnavailable:'Ova porudžbina više nije dostupna.', openOrderFailed:'Nije moguće otvoriti porudžbinu. Pokušajte ponovo.' },
  refund: { details:'Detalji refunda', full:'Pun refund', partial:'Delimičan refund', type:'Tip refunda', amount:'Refundirani iznos', reason:'Razlog refunda', explain:'Objasnite zbog čega je porudžbina refundirana', fullHelp:'Celokupna prodajna vrednost porudžbine biće automatski evidentirana.', maxPartial:'Maksimalni delimični refund', addDetails:'Dodaj detalje refunda', editDetails:'Izmeni detalje refunda', confirm:'Potvrdi refund', processing:'Obrada...', recordedHelp:'Ovim se porudžbina evidentira kao refundirana. Ova radnja ne izvršava refund na marketplace platformi.', reverse:'Poništi refundirani status', reverseHelp:'Ovim se ispravlja status u kontrolnoj tabli i uklanjaju aktivni podaci o refundu. Ova radnja ne poništava plaćanje na marketplace platformi.', confirmReversal:'Potvrdi poništavanje', reversing:'Poništavanje...', legacy:'Stari refund', legacyHelp:'Detaljne informacije o refundu nisu zabeležene za ovu porudžbinu.', unknownUser:'Nepoznat korisnik' },
  supplierAssignment: { reassign:'Promeni dobavljača', assign:'Dodeli dobavljača', select:'Izaberite dobavljača', noSupplier:'Nema aktivnih korisnika dobavljača.', saving:'Čuvanje...' },
  history: { title:'Istorija porudžbine', orderRefunded:'Porudžbina refundirana', refundUpdated:'Detalji refunda ažurirani', refundReversed:'Refundirani status poništen', changedBy:'Promenio', timeline:'Vremenska linija' },
  chat: { title:'Chat porudžbine', loading:'Učitavanje poruka...', empty:'Još nema poruka', refresh:'Osveži poruke', input:'Napišite poruku...', send:'Pošalji', sending:'Slanje...', hint:'Ctrl/Cmd+Enter za slanje', tooLong:'Poruka ne može imati više od 5000 znakova.', live:'Uživo', connecting:'Povezivanje', reconnecting:'Ponovno povezivanje...', offline:'Van mreže', edited:'Izmenjeno', admin:'Admin', seller:'Prodavac' },
};
